### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [LizIsTired/cave_dust#10]
Hello, the game was loading fine. I wanted to check if everything works correctly...
At the moment I was going near the Y position where the mod takes effect, I got this error log here:

java.lang.NoSuchFieldError: field_11141
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.lizistired.cavedust.CaveDustConfig.getParticle(CaveDustConfig.java:171)
	at net.lizistired.cavedust.CaveDust.createCaveDust(CaveDust.java:82)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62)
	at net.minecraft.client.MinecraftClient.handler$ehc000$onEndTick(MinecraftClient:16496)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1941)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by LizIsTired** [comment]
Thanks for opening an issue ticket, would you be able to remove _Not Enough Crashes_ and try again? _NEC_ is known to create invalid states because of how it works (this itself can CAUSE crashes) and it also blames mods when it's not always their fault. 

If it's still crashing after that, a full latest.log or crash log would be very appreiciated.

Updating to 1.19.3 is on the backburner regardless, I have other things going on but when I'm less busy it would be nice to know where to start.

**Comment by venaminecraft** [comment]
As you wish and thanks already 😊

**Crash:** 
java.lang.NoSuchFieldError: field_11141
	at net.lizistired.cavedust.CaveDustConfig.getParticle(CaveDustConfig.java:171)
	at net.lizistired.cavedust.CaveDust.createCaveDust(CaveDust.java:82)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62)
	at net.minecraft.cl
ass_310.handler$eih000$onEndTick(class_310.java:17496)
	at net.minecraft.class_310.method_1574(class_310.java:1941)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by LizIsTired** [comment]
Should be fixed with the latest release, check [Modrinth ](https://modrinth.com/mod/cave-dust/version/34OgoMtl )and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cave-dust/files/4352828)! (when it's approved haha)

**Comment by venaminecraft** [comment]
Thanks 🥳
